/**
 * CONCE — Serviço de Engenharia e Consultoria LTDA
 * Acervo Canônico de Composições Unitárias de Referência (SINAPI / SICRO / Próprias CONCE)
 */

import { BudgetComposition } from '@/types/budgetEngine'

export const CONCE_CANONICAL_COMPOSITIONS: BudgetComposition[] = [
  {
    id: 'comp-concreto-fck25',
    code: 'SINAPI-94964',
    description:
      'Concreto FCK 25MPa, traço 1:2,3:2,7 (em massa seca de cimento/areia média/brita 1) - preparo mecânico com betoneira 400 L',
    specialty: 'Estruturas & Fundações',
    unit: 'm³',
    source: 'SINAPI',
    version: 'v2.1',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-01-10',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Criação inicial base SINAPI SP',
      },
      {
        version: 'v2.1',
        date: '2025-02-15',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Atualização de insumos cimento CP II-E e brita basáltica',
      },
    ],
    inputs: [
      {
        id: 'inp-1',
        code: 'SINAPI-1379',
        description: 'Cimento Portland composto CP II-E-32',
        unit: 'kg',
        category: 'material',
        coefficient: 362.0,
        unitCost: 0.68,
      },
      {
        id: 'inp-2',
        code: 'SINAPI-370',
        description: 'Areia média lavada a granel',
        unit: 'm³',
        category: 'material',
        coefficient: 0.72,
        unitCost: 88.5,
      },
      {
        id: 'inp-3',
        code: 'SINAPI-4721',
        description: 'Pedra britada n. 1 (9,5 a 19 mm)',
        unit: 'm³',
        category: 'material',
        coefficient: 0.85,
        unitCost: 92.0,
      },
      {
        id: 'inp-4',
        code: 'SINAPI-88309',
        description: 'Pedreiro de edificações com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 2.4,
        unitCost: 26.5,
      },
      {
        id: 'inp-5',
        code: 'SINAPI-88316',
        description: 'Servente de obras com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 4.8,
        unitCost: 19.8,
      },
      {
        id: 'inp-6',
        code: 'SINAPI-5678',
        description: 'Betoneira capacidade de mistura 400 L motor elétrico trifásico 220V',
        unit: 'ch',
        category: 'equipamento',
        coefficient: 1.1,
        unitCost: 14.5,
      },
    ],
  },
  {
    id: 'comp-armacao-aco-ca50',
    code: 'SINAPI-92778',
    description:
      'Armação de estrutura convencional de concreto armado utilizando aço CA-50 de 10,0mm - montagem e fixação',
    specialty: 'Estruturas & Fundações',
    unit: 'kg',
    source: 'SINAPI',
    version: 'v1.4',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-03-01',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Base oficial SINAPI',
      },
      {
        version: 'v1.4',
        date: '2025-01-20',
        author: 'Equipe de Custos CONCE',
        changelog: 'Ajuste de perdas para 7% de arame e transpasse',
      },
    ],
    inputs: [
      {
        id: 'inp-7',
        code: 'SINAPI-337',
        description: 'Aço CA-50, 10,0 mm, vergalhão barra reta',
        unit: 'kg',
        category: 'material',
        coefficient: 1.07,
        unitCost: 7.95,
      },
      {
        id: 'inp-8',
        code: 'SINAPI-43132',
        description: 'Arame recozido 16 BWG, D = 1,65 mm',
        unit: 'kg',
        category: 'material',
        coefficient: 0.025,
        unitCost: 18.2,
      },
      {
        id: 'inp-9',
        code: 'SINAPI-88245',
        description: 'Armador de estrutura de concreto com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.075,
        unitCost: 26.8,
      },
      {
        id: 'inp-10',
        code: 'SINAPI-88316',
        description: 'Servente de obras com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.04,
        unitCost: 19.8,
      },
    ],
  },
  {
    id: 'comp-alvenaria-bloco-ceramico',
    code: 'SINAPI-87529',
    description:
      'Alvenaria de vedação de blocos cerâmicos furados 9x19x19cm (espessura 9cm) e argamassa de assentamento com preparo em betoneira',
    specialty: 'Alvenaria & Vedações',
    unit: 'm²',
    source: 'SINAPI',
    version: 'v2.0',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-02-12',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Composição padrão SINAPI SP',
      },
      {
        version: 'v2.0',
        date: '2025-03-05',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Inclusão de tela metálica eletrosoldada para amarração',
      },
    ],
    inputs: [
      {
        id: 'inp-11',
        code: 'SINAPI-684',
        description: 'Bloco cerâmico vazado para vedação 9 x 19 x 19 cm',
        unit: 'un',
        category: 'material',
        coefficient: 26.5,
        unitCost: 1.15,
      },
      {
        id: 'inp-12',
        code: 'SINAPI-87300',
        description: 'Argamassa traço 1:2:8 (cimento, cal e areia média) preparo mecânico',
        unit: 'm³',
        category: 'material',
        coefficient: 0.016,
        unitCost: 385.0,
      },
      {
        id: 'inp-13',
        code: 'SINAPI-88309',
        description: 'Pedreiro com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.85,
        unitCost: 26.5,
      },
      {
        id: 'inp-14',
        code: 'SINAPI-88316',
        description: 'Servente com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.42,
        unitCost: 19.8,
      },
    ],
  },
  {
    id: 'comp-emboço-interno',
    code: 'SINAPI-87775',
    description:
      'Emboço ou massa única em argamassa traço 1:2:8, preparo mecânico com betoneira, aplicada manualmente em panos de fachada/paredes internas, espessura 20mm',
    specialty: 'Revestimentos',
    unit: 'm²',
    source: 'SINAPI',
    version: 'v1.1',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-04-18',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Versão preliminar de emboço',
      },
      {
        version: 'v1.1',
        date: '2024-11-20',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Revisão de rendimento do pedreiro',
      },
    ],
    inputs: [
      {
        id: 'inp-15',
        code: 'SINAPI-87301',
        description: 'Argamassa traço 1:2:8 (cimento, cal hidratada e areia média) para emboço',
        unit: 'm³',
        category: 'material',
        coefficient: 0.024,
        unitCost: 395.0,
      },
      {
        id: 'inp-16',
        code: 'SINAPI-88309',
        description: 'Pedreiro com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.55,
        unitCost: 26.5,
      },
      {
        id: 'inp-17',
        code: 'SINAPI-88316',
        description: 'Servente com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.35,
        unitCost: 19.8,
      },
    ],
  },
  {
    id: 'comp-pintura-acrilica',
    code: 'SINAPI-88489',
    description:
      'Aplicação manual de pintura com tinta látex acrílica em paredes internas/externas, duas demãos com fundo selador',
    specialty: 'Pintura',
    unit: 'm²',
    source: 'SINAPI',
    version: 'v1.3',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-05-10',
        author: 'Equipe CONCE',
        changelog: 'Lançamento',
      },
      {
        version: 'v1.3',
        date: '2025-01-15',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Substituição por tinta acrílica premium standard ABNT NBR 15079',
      },
    ],
    inputs: [
      {
        id: 'inp-18',
        code: 'SINAPI-7356',
        description: 'Tinta látex acrílica premium antimofo acabamento fosco',
        unit: 'L',
        category: 'material',
        coefficient: 0.33,
        unitCost: 24.5,
      },
      {
        id: 'inp-19',
        code: 'SINAPI-6085',
        description: 'Selador acrílico base água para paredes',
        unit: 'L',
        category: 'material',
        coefficient: 0.16,
        unitCost: 14.2,
      },
      {
        id: 'inp-20',
        code: 'SINAPI-88310',
        description: 'Pintor com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.32,
        unitCost: 27.2,
      },
      {
        id: 'inp-21',
        code: 'SINAPI-88316',
        description: 'Servente de obras com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.12,
        unitCost: 19.8,
      },
    ],
  },
  {
    id: 'comp-ponto-eletrico',
    code: 'SINAPI-91924',
    description:
      'Ponto de tomada média 10A/250V embutida em parede, incluindo caixa 4x2", eletroduto flexível corrugado 3/4" e fiação 2,5mm²',
    specialty: 'Instalações Elétricas',
    unit: 'un',
    source: 'SINAPI',
    version: 'v1.0',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-06-01',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Criação inicial de ponto elétrico completo',
      },
    ],
    inputs: [
      {
        id: 'inp-22',
        code: 'SINAPI-1014',
        description: 'Cabo de cobre isolado 2,5 mm² flexível 750V (fase + neutro + terra)',
        unit: 'm',
        category: 'material',
        coefficient: 12.0,
        unitCost: 3.15,
      },
      {
        id: 'inp-23',
        code: 'SINAPI-2688',
        description: 'Eletroduto flexível corrugado PVC reforçado 3/4" (25mm)',
        unit: 'm',
        category: 'material',
        coefficient: 3.5,
        unitCost: 3.8,
      },
      {
        id: 'inp-24',
        code: 'SINAPI-38101',
        description: 'Módulo tomada 2P+T 10A 250V com placa 4x2"',
        unit: 'un',
        category: 'material',
        coefficient: 1.0,
        unitCost: 16.5,
      },
      {
        id: 'inp-25',
        code: 'SINAPI-88264',
        description: 'Eletricista com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.9,
        unitCost: 28.5,
      },
      {
        id: 'inp-26',
        code: 'SINAPI-88247',
        description: 'Ajudante de eletricista com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.6,
        unitCost: 21.0,
      },
    ],
  },
  {
    id: 'comp-conce-impermeabilizacao',
    code: 'CONCE-IMP-002',
    description:
      'Impermeabilização de laje com manta asfáltica elastomérica 4mm tipo III acabamento alumínio, primer e regularização traço 1:3',
    specialty: 'Serviços Preliminares',
    unit: 'm²',
    source: 'CONCE',
    version: 'v3.0',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2023-08-10',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Procedimento técnico CONCE para coberturas expostas',
      },
      {
        version: 'v2.5',
        date: '2024-05-14',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Adição de ensaio de estanqueidade 72h',
      },
      {
        version: 'v3.0',
        date: '2025-02-18',
        author: 'Eng. Edenir Souza da Rosa - CREA/RS-252397',
        changelog: 'Manta asfáltica polimérica classe B conforme NBR 9952',
      },
    ],
    inputs: [
      {
        id: 'inp-27',
        code: 'CONCE-MAT-044',
        description: 'Manta asfáltica 4mm poliéster aluminizada tipo III',
        unit: 'm²',
        category: 'material',
        coefficient: 1.15,
        unitCost: 52.0,
      },
      {
        id: 'inp-28',
        code: 'CONCE-MAT-045',
        description: 'Primer asfáltico base solvente para regularização',
        unit: 'L',
        category: 'material',
        coefficient: 0.4,
        unitCost: 19.5,
      },
      {
        id: 'inp-29',
        code: 'CONCE-MO-012',
        description: 'Impermeabilizador qualificado CONCE com maçarico a gás GLP',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.75,
        unitCost: 32.0,
      },
      {
        id: 'inp-30',
        code: 'SINAPI-88316',
        description: 'Servente de obras com encargos complementares',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.5,
        unitCost: 19.8,
      },
    ],
  },
  {
    id: 'comp-escavacao-mecanizada',
    code: 'SICRO-2S0110000',
    description:
      'Escavação mecânica em material de 1ª categoria até 2,00m de profundidade com retroescavadeira sobre rodas, bacia de contenção',
    specialty: 'Estruturas & Fundações',
    unit: 'm³',
    source: 'SICRO',
    version: 'v1.0',
    versionsHistory: [
      {
        version: 'v1.0',
        date: '2024-07-22',
        author: 'Equipe de Infraestrutura CONCE',
        changelog: 'Base SICRO DNIT',
      },
    ],
    inputs: [
      {
        id: 'inp-31',
        code: 'SICRO-E9515',
        description: 'Retroescavadeira de pneus potência 85 HP com caçamba padrão',
        unit: 'ch',
        category: 'equipamento',
        coefficient: 0.055,
        unitCost: 148.0,
      },
      {
        id: 'inp-32',
        code: 'SINAPI-88316',
        description: 'Servente para balizamento e acerto de fundo de vala',
        unit: 'h',
        category: 'mao_de_obra',
        coefficient: 0.12,
        unitCost: 19.8,
      },
    ],
  },
]

export const SPECIALTIES_LIST = [
  'Todas',
  'Estruturas & Fundações',
  'Alvenaria & Vedações',
  'Revestimentos',
  'Pintura',
  'Instalações Elétricas',
  'Instalações Hidrossanitárias',
  'Serviços Preliminares',
  'Infraestrutura & Pavimentação',
  'Demolições & Retiradas',
  'Estruturas Metálicas',
  'Telhados & Coberturas',
  'Esquadrias & Vidros',
  'Impermeabilização',
  'Pisos & Forros',
  'Instalações de Gás',
  'Climatização & Ventilação',
  'Sistemas de Prevenção e Combate a Incêndio',
  'Elevadores & Transporte Vertical',
  'Paisagismo & Urbanização',
  'Locação de Equipamentos',
  'Serviços Terceirizados',
]
